### ISSUE TITLE
Make this dries

### ISSUE THREAD

**Issue by TonyWAV** [WavUncraft/CTF#1]

**Comment by Driesboy** [comment]
Will start soon 
Worldreset?

**Comment by TonyWAV** [comment]
yup and make all messages and sign looks like on Svile plugins

**Comment by Driesboy** [comment]
ok

**Comment by TonyWAV** [comment]
start coding please

**Comment by Driesboy** [comment]
yes tomorrow

**Comment by Driesboy** [comment]
import the sw_svile here

**Comment by TonyWAV** [comment]
tell @ankitmaharjan252 to improt here or fork it

**Comment by ankitmaharjan252** [comment]
Sorry for the late response guys
Unfortunately i dont have my laptop now

**Comment by Driesboy** [comment]
if you set my server back on
i will make it tomorrow
